// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Achievements = Collections['achievements']['schema']['_output']
export declare const achievements: Achievements[]

export type Projects = Collections['projects']['schema']['_output']
export declare const projects: Projects[]

export type Work = Collections['workExperiences']['schema']['_output']
export declare const workExperiences: Work[]
